name: my first wf
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest  #Will Run On Container
        steps:
            - name: welcome msg
              run: echo "Hello Data Engineer"
