name: my first wf
on: push
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7

            - name: welcome msg
              run: echo "Hello Data Engineer"

            - name: install cowsay program
              run: sudo apt-get install cowsay -y

            - name: execute cowsay cmd
              run: cowsay -f dragon "Run For Cover, I am a Dragon....RAWR" >> dragon.txt
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: dragon-file
                path: dragon.txt
            
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon-file
                path: ./artifact_dir
            
            - name: Test File Exists
              run: grep -i "dragon" ./artifact_dir/dragon.txt

    deploy_job:
        needs: [test_job, build_job]
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon-file
                path: ./artifact_dir

            - name: Read File
              run: cat ./artifact_dir/dragon.txt

            - name: Checkout repo files
              run: ls
